### ISSUE TITLE
"Enhancement: Adding New Questions to Data Science Flashcards"

### ISSUE THREAD

**Issue by Divyansh200102** [klaus78/Data-Science-Flashcards#13]
I want to add questions in relavance to these topics
1.Machine Learning
2.Data Analysis
3.Statistics
Please assign this issue to me under the Hacktoberfest 2023 label

**Comment by klaus78** [comment]
Hi @Divyansh200102 you are welcome to contribute. Notice that there are also questions with "HELP NEEDED"

**Comment by Divyansh200102** [comment]
Please review and merge the pr @klaus78.

**Comment by Divyansh200102** [comment]
i will make the pr for help wanted questions asap. @klaus78

**Comment by Divyansh200102** [comment]
i have made the pr for the help wanted ques @klaus78 please review and merge it.
