### ISSUE TITLE
Back To Top Button 

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [klaus78/Data-Science-Flashcards#19]
Adding A Back to Top Button In a proper Responsive manner as No of Questions Are lot Then it will definitely become hard to again back to the top manually.

### Screenshots

![Screenshot 2023-10-24 083822](https://github.com/klaus78/Data-Science-Flashcards/assets/129049677/a141ed9f-90f5-4ab3-b8fe-cdc2f9af2d3a)

**Comment by Kapileswar-Moharana** [comment]
@klaus78 Assign this to me under Hacktoberfest, Already Ready just have to open the PR

**Comment by Kapileswar-Moharana** [comment]
@klaus78 ?

**Comment by klaus78** [comment]
@Kapileswar-Moharana at the moment if you double click on the bar on top, you go to the start of the page.

I did some experiments with buttons in the past but never found a good solution, also consider how a button would look like on mobile devices, thanks.

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana at the moment if you double click on the bar on top, you go to the start of the page.
> 
> I did some experiments with buttons in the past but never found a good solution, also consider how a button would look like on mobile devices, thanks.

Ok then M trying my best to do sir...

**Comment by klaus78** [comment]
thanks for your efforts

**Comment by Kapileswar-Moharana** [comment]
> thanks for your efforts

Should I left that bug on clicking h1 tag taking to top or fix it ?

**Comment by Kapileswar-Moharana** [comment]
@klaus78 ok sirr I am opening a pr check it thenn in 5 minutes just writing the pr tamplates
