### ISSUE TITLE
Adding Extra Question Regarding Machine Learning and Deep Learning

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [klaus78/Data-Science-Flashcards#7]
Supervised Learning:

Unsupervised Learning:

Deep Learning:

Evaluation and Metrics:

I have Some of the question under these topic ...

So Assign this issue to me under Hacktoberfest'23

**Comment by jahnavigundakaram** [comment]
Hi @klaus78! I have few questions and would like to contribute. Please assign this issue under Hacktoberfest'23. Thanks

**Comment by klaus78** [comment]
Hi @jahnavigundakaram you are welcome to contribute

**Comment by Divyansh200102** [comment]
Hi @klaus78! I have a few questions and would like to make a contribution. Please label this issue for Hacktoberfest'23. Thank you!

**Comment by Kapileswar-Moharana** [comment]
@klaus78   kindly check it sir #18 and merge it

**Comment by Kapileswar-Moharana** [comment]
@klaus78 ?

**Comment by klaus78** [comment]
Hi @Kapileswar-Moharana going to check it very soon thanks

**Comment by Kapileswar-Moharana** [comment]
> Hi @Kapileswar-Moharana going to check it very soon thanks

@klaus78 ok sir check it if any changes you want then let me know I will fix it
