### ISSUE TITLE
Adding Machine Learning Interview Questions

### ISSUE THREAD

**Issue by dhruvsaxena11** [klaus78/Data-Science-Flashcards#9]
Hi @klaus78 

I am a data science enthusiast.
I will add some new interview questions in Machine learning.
plz assign this issue to me under hacktoberfest 2023.

Thank you

**Comment by klaus78** [comment]
Hi @dhruvsaxena11 thank you for your help.

**Comment by dhruvsaxena11** [comment]
Update machine_learning.yml for ML Interview questions #11

plz kindly check and merge my pull request.

Thank you
@klaus78

**Comment by klaus78** [comment]
I added your questions @dhruvsaxena11 many thanks

**Comment by daavo03** [comment]
Hi i'd love to participate and add a participation to Hacktoberfest, I add the questions and send the PR under this issue?

**Comment by klaus78** [comment]
Yes correct :), I saw this too late
